blank_issues_enabled: true

issue_templates:
  - name: Bug Report
    description: Report a bug
    title: "[🐛 BUG] "
    labels: ["🐛 Bug"]
    body: "./ISSUE_TEMPLATE/bug_report.md"
    
  - name: Feature Request
    description: Propose a new feature or enhancement
    title: "[✨ FEATURE] "
    labels: ["✨ Feature"]
    body: "./ISSUE_TEMPLATE/feature_request.md"